import { createServerFn } from "@tanstack/react-start";
import { getMockAnswer, type AssistantAnswer } from "@/data/mockResponses";
import { getOptionalProviders } from "@/lib/ai/providers.server";

// Server-only orchestration. Provider credentials never reach the browser.
const SYSTEM_PROMPT = `You are the AI Medical & Research Assistant: an educational medical and biomedical research assistant. Help students, researchers, and general users understand medical and biomedical topics — not to replace a clinician.

Rules: provide general educational information; do not diagnose; do not prescribe or change medicines; distinguish established evidence from uncertainty; never invent citations, studies, statistics, or URLs; recommend appropriate professional/emergency care for urgent situations; explain limitations rather than guessing.

Response format: output ONLY valid JSON matching:
{"topic":string,"summary":string,"keyInformation":string[],"considerations":string[],"whenToSeekCare":string[],"sources":[{"title":string,"organization":string,"description":string,"url":string}]}`;

const RESPONSE_SCHEMA = {
  type: "object",
  properties: {
    topic: { type: "string" }, summary: { type: "string" },
    keyInformation: { type: "array", items: { type: "string" } },
    considerations: { type: "array", items: { type: "string" } },
    whenToSeekCare: { type: "array", items: { type: "string" } },
    sources: { type: "array", items: { type: "object", properties: { title: { type: "string" }, organization: { type: "string" }, description: { type: "string" }, url: { type: "string" } }, required: ["title", "organization", "description"] } },
  },
  required: ["topic", "summary", "keyInformation", "considerations", "whenToSeekCare", "sources"],
};

function isValidAnswer(value: unknown): value is AssistantAnswer {
  if (!value || typeof value !== "object") return false;
  const a = value as Record<string, unknown>;
  return typeof a.topic === "string" && typeof a.summary === "string" &&
    Array.isArray(a.keyInformation) && a.keyInformation.every((x) => typeof x === "string") &&
    Array.isArray(a.considerations) && a.considerations.every((x) => typeof x === "string") &&
    Array.isArray(a.whenToSeekCare) && a.whenToSeekCare.every((x) => typeof x === "string") &&
    Array.isArray(a.sources) && a.sources.every((x) => x && typeof x === "object" && typeof (x as any).title === "string" && typeof (x as any).organization === "string" && typeof (x as any).description === "string");
}

type AskAssistantRequest = { question?: unknown };
function isRequest(data: unknown): data is { question: string } { return typeof data === "object" && data !== null && typeof (data as AskAssistantRequest).question === "string"; }

export const askAssistant = createServerFn({ method: "POST" })
  .validator((data: unknown) => { if (!isRequest(data)) throw new Error("Invalid request payload."); return data; })
  .handler(async ({ data }): Promise<AssistantAnswer> => {
    const providers = getOptionalProviders(RESPONSE_SCHEMA);
    if (providers.length === 0) {
      console.warn("No AI provider is configured; using curated medical reference responses.");
      return getMockAnswer(data.question);
    }

    for (const provider of providers) {
      try {
        const answer = await provider.generate(data.question, SYSTEM_PROMPT);
        if (isValidAnswer(answer)) {
          console.info(`AI response generated by ${provider.label}.`);
          return answer;
        }
        console.warn(`${provider.label} returned an invalid response shape; trying next provider.`);
      } catch (error) {
        console.warn(`${provider.label} unavailable; trying next provider.`, error);
      }
    }

    console.warn("All configured AI providers failed; using curated medical reference responses.");
    return getMockAnswer(data.question);
  });
